# (from: https://qiita.com/masashi127/items/5bfcba5cad8e82958844)

language: python

python:
  - 3.4
  - 3.5
  - 3.6

addons:
  apt:
    packages:
    # (from: https://github.com/dnouri/nolearn/blob/master/.travis.yml)
    - libblas-dev
    - liblapack-dev
    - gfortran


before_install:
  - pip install -U pip setuptools wheel # (from: https://github.com/dnouri/nolearn/blob/master/.travis.yml)

install:
  - pip install pipenv

script:
  - pipenv install
  - pipenv install --dev
  - pipenv run coverage run --source=multi_svr setup.py test

  - pip3 install --upgrade git+https://github.com/nwtgck/multi-svr-python.git#$TRAVIS_COMMIT
  - python examples/example1.py

after_success:
  - coveralls

cache:
  - apt
  - directories:
    - $HOME/.cache/pip